#!/usr/bin/env python3
"""
Converts pure Lua libraries into a C file that preloads them into Lua's package.preload table.
"""

import os
import sys
from pathlib import Path

# Define libraries to embed: (module_name, path_to_lua_file)
LIBRARIES = [
    ("json", "json/json.lua"),
    ("inspect", "inspect/inspect.lua"),
    ("serpent", "serpent/src/serpent.lua"),
    ("classic", "classic/classic.lua"),
    ("middleclass", "middleclass/middleclass.lua"),
    # Functional programming
    ("moses", "moses/moses.lua"),
    ("fun", "luafun/fun.lua"),
    # Animation/tweening
    ("flux", "flux/flux.lua"),
    # Penlight has multiple modules - add the main ones
    ("pl.utils", "penlight/lua/pl/utils.lua"),
    ("pl.tablex", "penlight/lua/pl/tablex.lua"),
    ("pl.stringx", "penlight/lua/pl/stringx.lua"),
    ("pl.path", "penlight/lua/pl/path.lua"),
    ("pl.pretty", "penlight/lua/pl/pretty.lua"),
]

def escape_c_string(content: str) -> str:
    """Escape a string for embedding in C."""
    result = []
    for char in content:
        if char == '\\':
            result.append('\\\\')
        elif char == '"':
            result.append('\\"')
        elif char == '\n':
            result.append('\\n')
        elif char == '\r':
            result.append('\\r')
        elif char == '\t':
            result.append('\\t')
        elif ord(char) < 32 or ord(char) > 126:
            # Use octal escapes instead of hex to avoid issues with following hex digits
            result.append(f'\\{ord(char):03o}')
        else:
            result.append(char)
    return ''.join(result)

def generate_c_file(base_path: Path) -> str:
    """Generate the C file content."""
    lines = [
        "/*",
        " * Auto-generated file - do not edit!",
        " * Contains embedded pure Lua libraries for WASM build.",
        " * Generated by build_purelibs.py",
        " */",
        "",
        '#include "lua.h"',
        '#include "lauxlib.h"',
        '#include "lualib.h"',
        "",
        "/* Embedded Lua library sources */",
        "",
    ]
    
    loaded_libs = []
    
    for module_name, rel_path in LIBRARIES:
        lua_path = base_path / rel_path
        if not lua_path.exists():
            print(f"Warning: {lua_path} not found, skipping {module_name}", file=sys.stderr)
            continue
        
        content = lua_path.read_text(encoding='utf-8')
        escaped = escape_c_string(content)
        var_name = module_name.replace(".", "_")
        
        lines.append(f"static const char {var_name}_src[] = \"{escaped}\";")
        lines.append("")
        loaded_libs.append((module_name, var_name))
    
    # Generate the loader function
    lines.extend([
        "/* Loader function for a preloaded module */",
        "static int preload_loader(lua_State *L) {",
        "    const char *src = lua_tostring(L, lua_upvalueindex(1));",
        "    const char *name = lua_tostring(L, lua_upvalueindex(2));",
        "    if (luaL_loadstring(L, src) != 0) {",
        "        return lua_error(L);",
        "    }",
        "    lua_pushstring(L, name);",
        "    lua_call(L, 1, 1);",
        "    return 1;",
        "}",
        "",
        "/* Register all pure Lua libraries into package.preload */",
        "LUALIB_API void luaL_openpurelibs(lua_State *L) {",
        '    luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);',
        "",
    ])
    
    for module_name, var_name in loaded_libs:
        lines.extend([
            f'    /* {module_name} */',
            f'    lua_pushstring(L, {var_name}_src);',
            f'    lua_pushstring(L, "{module_name}");',
            f'    lua_pushcclosure(L, preload_loader, 2);',
            f'    lua_setfield(L, -2, "{module_name}");',
            "",
        ])
    
    lines.extend([
        "    lua_pop(L, 1); /* pop preload table */",
        "}",
        "",
    ])
    
    return '\n'.join(lines)

def main():
    base_path = Path(__file__).parent
    output_path = base_path / "purelibs.c"
    
    c_content = generate_c_file(base_path)
    output_path.write_text(c_content, encoding='utf-8')
    
    print(f"Generated {output_path}")
    print(f"Add this to your build: {output_path.name}")

if __name__ == "__main__":
    main()
